name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install FFmpeg
        run: choco install ffmpeg -y
      - run: npm ci
      - run: npm run build
      - uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v0.1.0
          releaseName: 'UberEditor Windows v0.1.0'
          releaseBody: 'Windows build'
          releaseDraft: false
          prerelease: false
